all:
	cd common; make common
	cd client; make client.exe
	cd monitor; make monitor.exe
	cd server; make server.exe

clean:
	cd client; make clean
	cd common; make clean
	cd monitor; make clean
	cd server; make clean
